---
deployment:
  tasks:
    - npm install
    - npm run build
    - export DEPLOYPATH=/home/sercanbaris/public_html
    - /bin/cp -r dist/* $DEPLOYPATH/
    - echo "Deployment completed successfully."
